efs/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, LogoutView, LoginView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include, re_path
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    #url(r'^accounts/login/$', views.login, name='login'),
    #url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(template_name='registration/logout.html'), LogoutView.next_page, name="logout"),

    re_path(r'^accounts/password/reset/$',
            PasswordResetView.as_view(template_name='registration/password_reset_page.html'), name='password_reset'),
    re_path(r'^accounts/password/reset/done/$',
            PasswordResetDoneView.as_view(template_name='registration/passwordreset_pagedone.html'),
            name='password_reset_done'),
    re_path(
        r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirmpage.html'),
        name='password_reset_confirm'),
    re_path(r'^accounts/password/reset/complete/$',
            PasswordResetCompleteView.as_view(template_name='registration/password_reset_completepage.html'),
            name='password_reset_complete'),

    re_path(r'^accounts/password/change/$',PasswordChangeView.as_view(template_name = 'registration/change-password.html'), name='password_change'),
    re_path(r'^accounts/password/change/done/$',PasswordChangeDoneView.as_view(template_name='registration/change-password-done.html'),
            name='password_change_done'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from . import views
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'portfolio'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('customer/new/create', views.customer_new, name='customer_new'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
    path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),
    path('stock/create/', views.stock_new, name='stock_new'),
    path('investment_list', views.investment_list, name='investment_list'),
    path('investment/<int:pk>/edit/', views.investment_edit, name='investment_edit'),
    path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),
    path('investment/create/', views.investment_new, name='investment_new'),
    path('register/', views.register, name='register'),
    path('customer/<int:pk>/portfolio', cache_page(60 * 5)(views.portfolio), name='portfolio'),
    path('customer/<int:pk>/portfolio/downloadpdf',views.downloadpdf, name='downloadpdf'),

    path('customer/<int:pk>/summarygraph/', views.summarygraph, name='summarygraph'),

    path('email/<int:pk>/', views.email, name='email'),
    #path('customer/<int:pk>/customer_summary/', views.customer_summary, name='customer_summary'),
    url(r'^customers_json/', views.CustomerList.as_view()),

]

urlpatterns = format_suffix_patterns(urlpatterns)

portfolio/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Customer, Stock, Investment, Mails


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date',)
        widgets = {
            'purchase_date': forms.DateInput(attrs={'class': 'datepicker', 'type': 'date', }),

        }


class InvestmentForm(forms.ModelForm):
    class Meta:
        model = Investment
        fields = ('customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value','recent_date')
        widgets = {
            'acquired_date': forms.DateInput(attrs={'class': 'datepicker', 'type': 'date', }),
            'recent_date': forms.DateInput(attrs={'class': 'datepicker', 'type': 'date', }),

        }


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username', 'email','first_name','last_name', 'password1', 'password2',)


class EmailForm(forms.ModelForm):
    email = forms.EmailField(max_length=200,
                             widget=forms.TextInput(attrs={'class': "form-control", 'id': "clientemail"}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': "form-control"}))
    subject = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}))

    class Meta:
        model = Mails
        fields = ('email', 'subject', 'message', 'document',)

portfolio/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import EmailMessage
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import get_template
from django.urls import reverse
from django.db.models import Sum
from django.views import View
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from .fusioncharts import FusionCharts
from .serializers import CustomerSerializer
from decimal import Decimal
from .models import *
from .forms import *
from .utils import render_to_pdf
from django.views.decorators.cache import cache_page
now = timezone.now()


def home(request):
    return render(request, 'portfolio/home.html',
                 {'portfolio': home})


@login_required
def customer_list(request):
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/customer_list.html',{'customers': customers})


@login_required
def customer_edit(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == "POST":
        # update
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.updated_date = timezone.now()
            customer.save()
            #customer = Customer.objects.filter(created_date__lte=timezone.now())
            #return render('portfolio/customer_list.html',{'customers': customer})
            return redirect('portfolio:customer_list')
    else:
        form = CustomerForm(instance=customer)
    return render(request, 'portfolio/customer_edit.html', {'form': form})


@login_required
def customer_delete(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customer.delete()
    return redirect('portfolio:customer_list')


@login_required
def customer_new(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.created_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter(created_date__lte=timezone.now())
            #context= {'customers': customer}
            return redirect('portfolio:customer_list')
            #return redirect(reverse('portfolio:customer_list'),context)
            #return HttpResponseRedirect(reverse('portfolio:customer_list'), context)
    else:
        form = CustomerForm()
    return render(request, 'portfolio/customer_new.html', {'form': form})


@login_required
def stock_list(request):
    stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
    return render(request, 'portfolio/stock_list.html', {'stocks': stocks})


@login_required
def stock_new(request):
    if request.method == "POST":
        form = StockForm(request.POST)
        if form.is_valid():
            stock = form.save(commit=False)
            stock.created_date = timezone.now()
            stock.save()
            #stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            #return render(request, 'portfolio/stock_list.html',{'stocks': stocks})
            return redirect('portfolio:stock_list')
    else:
        form = StockForm()
        # print("Else")
    return render(request, 'portfolio/stock_new.html', {'form': form})


@login_required
def stock_edit(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    if request.method == "POST":
        form = StockForm(request.POST, instance=stock)
        if form.is_valid():
            stock = form.save()
            # stock.customer = stock.id
            stock.updated_date = timezone.now()
            stock.save()
            #stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            #return render(request, 'portfolio/stock_list.html', {'stocks': stocks})
            return redirect('portfolio:stock_list')
    else:
        # print("else")
        form = StockForm(instance=stock)
    return render(request, 'portfolio/stock_edit.html', {'form': form})


@login_required
def stock_delete(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    stock.delete()
    return redirect('portfolio:stock_list')


@login_required
def investment_list(request):
    investments = Investment.objects.filter(acquired_date__lte=timezone.now())
    return render(request, 'portfolio/investment_list.html', {'investments': investments})


@login_required
def investment_new(request):
    if request.method == "POST":
        form = InvestmentForm(request.POST)
        if form.is_valid():
            investment = form.save(commit=False)
            investment.created_date = timezone.now()
            investment.save()
            #stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            #return render(request, 'portfolio/stock_list.html',{'stocks': stocks})
            return redirect('portfolio:investment_list')
    else:
        form = InvestmentForm()
        # print("Else")
    return render(request, 'portfolio/investment_new.html', {'form': form})


@login_required
def investment_edit(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    if request.method == "POST":
        form = InvestmentForm(request.POST, instance=investment)
        if form.is_valid():
            investment = form.save()
            # stock.customer = stock.id
            investment.updated_date = timezone.now()
            investment.save()
            #stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            #return render(request, 'portfolio/stock_list.html', {'stocks': stocks})
            return redirect('portfolio:investment_list')
    else:
        # print("else")
        form = InvestmentForm(instance=investment)
    return render(request, 'portfolio/investment_edit.html', {'form': form})


@login_required
def investment_delete(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    investment.delete()
    return redirect('portfolio:investment_list')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            advisor_group = Group.objects.get_or_create(name='Advisor')
            advisor_group[0].user_set.add(user)
            return render(request,'registration/registerdone.html', {'form': form})
    else:
        form = RegisterForm()
    return render(request, "registration/register.html", {"form": form})


@login_required
def portfolio(request,pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    investments = Investment.objects.filter(customer=pk)
    stocks = Stock.objects.filter(customer=pk)
    sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
    #print("sum_recent_value: " + str(sum_recent_value))
    #print(type(sum_recent_value))
    sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
    #print("sum_acquired_value: " + str(sum_acquired_value))
    #print(type(sum_acquired_value))
    #overall_investment_results = sum_recent_value - sum_acquired_value--it is not working unsupported dict operands
    #overall_investment_results = sum_recent_value['recent_value__sum'] - sum_acquired_value['acquired_value__sum']
    overall_investment_results = Decimal(sum_recent_value.get('recent_value__sum')) - Decimal(sum_acquired_value.get('acquired_value__sum'))
    print("overall_investment_results:",overall_investment_results)
    #print("overall_investment_results1:", overall_investment_results1)
    # overall_investment_results = Decimal(sum_recent_value['recent_value__sum']) - Decimal(sum_acquired_value['acquired_value__sum'])
    #print(" overall_investment_results:" + str(overall_investment_results))

    # Initialize the value of the stocks
    sum_current_stocks_value = 0
    sum_of_initial_stock_value = 0

    # Loop through each stock and add the value to the total
    for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        #print(type((stock.current_stock_value())))
        #print(sum_current_stocks_value)
        #print("sum_current_stocks_value " + str(sum_current_stocks_value))
        sum_of_initial_stock_value += stock.initial_stock_value()
        #print(type((stock.initial_stock_value())))
        #print(sum_of_initial_stock_value)
        #print("sum_of_initial_stock_value " + str(sum_of_initial_stock_value))

    #overall_stocks_results = sum_current_stocks_value - sum_of_initial_stock_value
    # unsupported operand type(s) for -: 'float' and 'decimal.Decimal' for this line
    #overall_stocks_results = Decimal(sum_current_stocks_value) - Decimal(sum_of_initial_stock_value)
    overall_stocks_results = float(sum_current_stocks_value) - float(sum_of_initial_stock_value)
    #print(type(overall_stocks_results))
    #print("overall_stocks_results" + str(overall_stocks_results))
    return render(request, 'portfolio/portfolio.html', {'customer': customer,'investments': investments,
                                                        'stocks': stocks,
                                                        'sum_acquired_value': sum_acquired_value,
                                                        'sum_recent_value': sum_recent_value,
                                                        'sum_current_stocks_value': sum_current_stocks_value,
                                                        'sum_of_initial_stock_value': sum_of_initial_stock_value,
                                                        'overall_stocks_results': overall_stocks_results,

portfolio/templates/portfolio/base.html
{% load static %}

<html lang="en">
<head>
<title>Eagle Financial Services</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Eagle Financial Services</title>
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="{% static 'fusioncharts/fusioncharts.js' %}"></script>
    <script type="text/javascript" src="{% static 'fusioncharts/themes/fusioncharts.theme.fint.js' %}"></script>
    <script type="text/javascript" src="{% static 'fusioncharts/fusioncharts.charts.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script type="text/javascript" src="{% static 'fusioncharts/themes/fusioncharts.theme.fusion.js' %}"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'css/portfolio.css' %}">
</head>

 <style>
      .navbar {
        margin-bottom: 0;
        border-radius: 0;
    }

       .container .row .col-md-12 .card {
        background: rgb(0, 0, 0);
        background: rgba(0, 0, 0, 0.1);
        color: blue;
    }
      .table{
        width : 165%;
        table-layout: fixed;
        border-collapse: collapse;
        word-wrap: break-word;
    }
       .content {
        padding-left: 8px;
    }


    </style>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark mb-4">
        <a href="/" class="navbar-brand">Eagle Financial Services</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                 {% if user.is_authenticated and user.is_superuser  or user.groups.all.0.name == "Advisor" %}
                <li class="nav-item active"><a class=nav-link href="{% url 'portfolio:home' %}">Home</a></li>
                <li class="nav-item active"><a class=nav-link href="{% url 'portfolio:customer_list' %}">Customers</a></li>
                <li class="nav-item active"><a class=nav-link href="{% url 'portfolio:investment_list' %}">Investment</a></li>
                <li class="nav-item active"><a class=nav-link href="{% url 'portfolio:stock_list' %}">Stocks</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                    </div>
                    </li>
            </ul>

                {% else %}
                <form class="form-inline my-2 my-lg-0">
                    <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log In</a>
                    <a href="{% url 'portfolio:register' %}" class="btn btn-primary ml-2">Sign Up</a>
                </form>
                {% endif %}

            </ul>
        </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static 'images/customers.jpg' %}" alt="customers"/>
                                <div class="caption">
                                    <h2>Customer</h2>
                                    <p>We see our success in our customers success, it gives us an immense pleasure when
                                        our
                                        advises
                                        turn out to be fruitful. </p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'portfolio:customer_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
<img src="{% static 'images/nonstock.jpg' %}" alt="non-stock"/>
                                <div class="caption">
                                    <h2>Non-Stock Investments</h2>
                                    <p>Our team also provides advice for Non-Stock investments.</p>
                                    <p><a class="btn btn-default" href="{% url 'portfolio:investment_list' %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static 'images/stocks.jpg' %}" alt="stocks"/>
                                <div class="caption">
                                    <h2>Stock Portfolio</h2>
                                    <p>Our Stock portfolios vary across industries.</p>
                                    <p><a class="btn btn-default" href="{% url 'portfolio:stock_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</div>

</div>


</body>

</html>

portfolio/templates/portfolio/customer_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


    <h1>Edit Customer</h1>
       <form action="" method="post">{% csrf_token %}
       {{ form|crispy }}
        <button type="submit" class="save btn btn-primary">Update</button>
    </form>
</body>
{% endblock %}

portfolio/templates/portfolio/customer_list.html
{% extends 'portfolio/base.html' %}
{% block content %}
<html>
<body>


<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">Welcome!</div>
                    <p class="card-text">
                    Eagle Financial Services, your Midwest Financial Services Partner
                    </p>
                </div>
            </div>
        </div>
    </div>


<div class="row"><br>

    <h2 style="padding-left: 15Px"><u>Customer Information</u></h2>
</div>
     {% if customers %}
    <div>
        <table class="table table-hover table-responsive-lg text-center">
            <thead>
           <tr class="bg-warning">
                <th>Customer Number</th>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Primary Email</th>
                <th>Cell Phone</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr bgcolor="white">
                    <td>{{ customer.cust_number }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.cell_phone }}</td>

                      <td><a href="{% url 'portfolio:customer_edit' pk=customer.pk %}"
                           class="btn btn-warning">Edit</a><br><br><a href="{% url 'portfolio:summarygraph' pk=customer.pk %}"
                           class="btn btn-warning">Summary</a></td>

                     <td><a href="{% url 'portfolio:customer_delete' pk=customer.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                         <br><br>
                         <a href="{% url 'portfolio:email' pk=customer.pk %}"
                           class="btn btn-danger">Send Email</a></td>


                     <td><a href="{% url 'portfolio:portfolio' pk=customer.pk %}"
                           class="btn btn-primary">Portfolio</a><br><br>
                         <a href="{% url 'portfolio:downloadpdf' pk=customer.pk %}"
                           class="btn btn-primary">Portfolio PDF</a></td>


                </tr>
            {% endfor %}
            </tbody>
        </table>
         {% else  %}
        <div class="col-md-12" style="text-align: center;">
            <div >
                <p class="lead">
                  No Records Available
                </p>
            </div>
        </div>

     {% endif %}
         {% if user.is_authenticated and user.is_superuser%}
         <div class="row">
             <a href="{% url 'portfolio:customer_new' %}" class="row"><span
                    class="btn btn-primary">Add Customer</span></a>

        </div>
        {% endif %}

    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/customer_new.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


    <h1>Add New Customer</h1>
       <form action="" method="post">{% csrf_token %}
       {{ form|crispy }}
        <button type="submit" class="save btn btn-primary">Add</button>
    </form>
</body>
{% endblock %}

portfolio/templates/portfolio/investment_list.html
{% extends 'portfolio/base.html' %}
{% block content %}


<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">Welcome!</div>
                    <p class="card-text">
                    Eagle Financial Services, your Midwest Financial Services Partner
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <h2 style="padding-left: 15Px"><u>Investment Information</u></h2>
    </div>
    <div>
        <table class="table table-hover table-responsive-lg text-center">
            <thead>
           <tr class="bg-warning">
                <th>Customer number</th>
                <th>Category</th>
                <th>Description</th>
                <th>Acquired value</th>
                <th>Acquired Date</th>
                <th>Recent Value</th>
                <th>Recent Date</th>
                <th colspan="2">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for investment in investments %}
                <tr bgcolor="white">
                    <td>{{ investment.customer }}</td>
                    <td>{{ investment.category }}</td>
                    <td>{{ investment.description }}</td>
                    <td>{{ investment.acquired_value }}</td>
                    <td>{{ investment.acquired_date }}</td>
                    <td>{{ investment.recent_value }}</td>
                    <td>{{ investment.recent_date }}</td>
                    <td><a href="{% url 'portfolio:investment_edit' pk=investment.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'portfolio:investment_delete' pk=investment.pk %}"
                    onclick="return confirm('Are you sure you want to delete?')"
                    class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

     <div class="row">
            <a href="{% url 'portfolio:investment_new' %}" class="row"><span
                    class="btn btn-primary">Add Investment</span></a>
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/sent.html
<!DOCTYPE html>
<html lang="en">
{% extends 'portfolio/base.html' %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>sent</title>
    </head>
    <body>
        <h1>Sent an email!</h1>
    </body>
</html>
{% endblock %}

portfolio/templates/portfolio/stock_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">Welcome!</div>
                    <p class="card-text">
                    Eagle Financial Services, your Midwest Financial Services Partner
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <h2 style="padding-left: 15Px"><u>Stocks Information</u></h2>
    </div>
    <div>
        <table class="table table-hover table-responsive-lg text-center">
            <thead>
            <tr class="bg-warning">
                <th>Customer number</th>
                <th>Symbol</th>
                <th>Name</th>
                <th>Shares</th>
                <th>Purchase Price</th>
                <th>Purchase Date</th>
                <th colspan="2">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for stock in stocks %}
                <tr bgcolor="white">
                    <td>{{ stock.customer }}</td>
                    <td>{{ stock.symbol }}</td>
                    <td>{{ stock.name }}</td>
                    <td>{{ stock.shares }}</td>
                    <td>{{ stock.purchase_price }}</td>
                    <td>{{ stock.purchase_date }}</td>
                    <td><a href="{% url 'portfolio:stock_edit' pk=stock.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'portfolio:stock_delete' pk=stock.pk %}"
                    onclick="return confirm('Are you sure you want to delete?')"
                    class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

     <div class="row">
            <a href="{% url 'portfolio:stock_new' %}" class="row"><span
                    class="btn btn-primary">Add Stock</span></a>
        </div>
    </div>
</div>
{% endblock %}